name: lint_python
on: [pull_request, push, workflow_dispatch]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install --upgrade pip wheel setuptools
      - run: pipx run codespell --ignore-words-list="commend"
      - run: pip install mypy pytest ruff
      - run: ruff format --check --config "format.quote-style = 'single'"
      - run: ruff check --output-format=github --select=ALL --ignore=D203,D212,Q000
      - run: pip install -r requirements.txt || pip install --editable . || true
      - run: mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive .
      - run: pytest . || pytest --doctest-modules . || true
